[package]
edition = "2021"
name = "personal-space"
version = "0.1.0"

[dependencies]
prost = "0.11"
tokio = {version = "1.0", features = ["macros", "rt-multi-thread"]}
tonic = "0.8"

[build-dependencies]
tonic-build = "0.8"
