[default]
address = "127.0.0.1"
cli_colors = true
ident = "Nginx"
keep_alive = 5
log_level = "normal"
max_blocking = 512
port = 8000
temp_dir = "/tmp"
workers = 16

[default.mongodb]
database = "falcon"
url = "mongodb+srv://yuang:<password>@cluster0.suglge8.mongodb.net/?retryWrites=true&w=majority"
